os: osx
osx_image: xcode9.1
language: swift
xcode_workspace: SaltChannel.xcworkspace

env:
  - SWIFT_VERSION=4.0

notifications:
  email:
    recipients:
      - kenneth@pernyer.se
      - hakan.ohlsson@assaabloy.com
    on_success: never
    on_failure: always
