language: swift
os: osx
osx_image: xcode9.4
xcode_workspace: SaltChannel.xcworkspace
xcode_scheme: SaltChannel-Tests

script:
  - make all

env:
  - SWIFT_VERSION=4.1

notifications:
  email:
    recipients:
      - dreadrik@gmail.com
    on_success: never
    on_failure: always
