language: swift
os: osx
osx_image: xcode9.4
xcode_workspace: SaltChannel.xcworkspace
xcode_scheme: SaltChannel-Tests

install:
  - pod outdated | awk '{ if ( $1 ~ /^-/ ) { print $0 } }' | awk '{ if ( $3 != $5 ) { pod update $2 } else { print "No updated needed for" $2 } }'

script:
  - make all

env:
  - SWIFT_VERSION=4.1

notifications:
  email:
    recipients:
      - dreadrik@gmail.com
    on_success: never
    on_failure: always
